[package]
name = "tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "array_tree"           # The name of the target.
path = "src/arraytree.rs"    # The source file of the target.

[dependencies]
